routes/web.php
<?php

use App\Http\Controllers\ProyectosController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//agregado en clase 01/02/24//

Route::resource("proyecto", ProyectosController::class);

app/Models/Proyectos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyectos extends Model
{
    use HasFactory;
    // agregado el 15/02 en clase
    protected $fillable = ['nombre', 'descripcion'];
}

app/Models/User.php
    
    <?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\View\View;
use Illuminate\Support\Facades\DB;
use App\Models\Proyectos;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //agregado en clase//
        $proyectos = DB::table("proyectos")->get();
        // $descripcionProyectos = DB::table("proyectos.descripcion")->get();
        return view("proyecto.index",["proyectos"=>$proyectos]);
    }
    // ,["descripcionProyectos"=>$descripcionProyectos]
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response    
     */
    public function create(): View
    {
        //agregado el 08/02 en clase
        return view("proyecto.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request): RedirectResponse
    {
        //agregado el 08/02 en clase
        $request->validate([
            'nombre' => 'required|max:255',
            'descripcion' => 'required',
        ]);
        // dd($request->all());
        Proyectos::create($request->all());
        return redirect()->route('proyecto.index') ->with('success','Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Proyectos  $proyectos
     * @return \Illuminate\Http\Response
     */
    public function show(Proyectos $proyectos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Proyectos  $proyectos
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // agregado el 14/02 con el código subido por la miss a las 9 pm
        $proyecto = Proyectos::find($id);
        return view('proyecto.edit', compact('proyecto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Proyectos  $proyectos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Proyectos  $proyecto)
    {
        // agregado el 14/02 con el código subido por la miss a las 9 pm
        $request->validate([
                'nombre' => 'required|max:255',
                'descripcion' => 'required',
            ]);
        // $proyecto = Proyectos::find($id);
        $proyecto->update($request->all());
        return redirect()->route('proyecto.index')
        ->with('success','El proyecto se ha actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Proyectos  $proyectos
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // agregado el 14/02 con el código subido por la miss a las 9 pm
        $proyecto = Proyectos::find($id);
        $proyecto->delete();
        return redirect()->route('proyecto.index')
            ->with('success', 'el proyecto ha sido eliminado correctamente');
    }
}

resources/views/proyecto/create.blade.php
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
    @if ($errors->any())
    <div class="alert alert-danger mt-2">
        <strong>Este es un mensaje de error...</strong> Algo fue mal..<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div>
      <a href="{{route('proyecto.index')}}" class="btn btn-primary">Volver</a>
    </div>
    <form action="{{route('proyecto.store')}}" method="post">
    	@csrf
      <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
              <div class="form-group">
                  <strong>Nombre proyecto:</strong>
                  <input type="text" name="nombre" class="form-control" placeholder="Nombre" >
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
              <div class="form-group">
                  <strong>Descripción:</strong>
                  <textarea class="form-control" style="height:150px" name="descripcion" placeholder="Descripción..."></textarea>
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-2">
              <button type="submit" class="btn btn-primary">Crear</button>
          </div>
      </div>
    </form>
  </body>
</html>

resources/views/proyecto/edit.blade.php
<style>
    :root {
        --background-color: #7c8994;
        --text-color: #333;
        --container-bg: #fff;
        --container-shadow: rgba(0, 0, 0, 0.1);
        --form-bg: blanchedalmond;
        --border-radius: 10px;
        --form-spacing: 20px;
    }

    body {
        font-family: sans-serif;
        margin: 0;
        padding: 0;
        background-color: var(--background-color);
        color: var(--text-color);
    }

    .container {
        width: 80%;
        margin: 2em auto;
        background: var(--container-bg);
        padding: var(--form-spacing);
        box-shadow: 0 0 10px var(--container-shadow);
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    .form-group {
        margin-bottom: var(--form-spacing);
    }

    .form-group label {
        display: block;
        margin-bottom: 0.5em;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 0.5em;
        border-radius: var(--border-radius);
        background-color: var(--form-bg);
        border: 1px solid #ccc;
        margin-bottom: 1em;
    }

    .btn {
        padding: 0.5em 1em;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: var(--border-radius);
        cursor: pointer;
    }

    .btn.primary {
        background-color: #0056b3;
    }

    .btn + .btn {
        margin-left: 0.5em;
    }

    .btn:hover {
        background-color: #0069d9;
    }

    a {
        color: var(--text-color);
        text-decoration: none;
        padding: 0.5em 1em;
        display: inline-block;
    }

    a:hover {
        text-decoration: underline;
    }
</style>

<div class="container">
    <form action="{{ route('proyecto.update', $proyecto->id) }}" method="post">
        @csrf
        @method("put")
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" value="{{ $proyecto->nombre }}" required>
        </div>
        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <textarea class="form-control" id="descripcion" name="descripcion" rows="3" required>{{ $proyecto->descripcion }}</textarea>
        </div>
        <button type="submit" class="btn primary">Actualizar</button>
        <a href="{{ route('proyecto.index') }}" class="btn">Volver</a>
    </form>
</div>

resources/views/proyecto/index.blade.php
<html>
	<head>
		<style type="text/css">
			body{
				font-family: sans-serif;
				margin: 2em;
                padding: 2em;
                background-color: #7c8994;
			}
			.container{
				width: 80%;
                margin: 0 auto;
                background: white;
                padding: 20px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
			}
			h1 {
                color: #333;
            }

            h2 {
                color: #666;
/*                border-bottom: #3333b8b0;*/
            }

            li {
                margin-bottom: 10px;
            }

            /*.container .proyectos{
            	background-color: #3333b8b1;
            	border-bottom: #3333b8b0;
            	border-bottom: #0a0a21;
            	padding: 0.5em 0;
            	margin-bottom: 1.5em;
            	border-color: #3333b8b0;
            }*/

            /*ESTILOS PARA LA TABLA*/
            table {
                width: 100%;
                border-collapse: collapse;
            }

            th, td {
                padding: 8px;
                text-align: left;
                border-bottom: 1px solid #ddd;
            }

            tr:hover {background-color: #f5f5f5;}

            th {
                background-color: #f4f4f4;
                color: black;
            }

		</style>

	</head>
	<body>
		<div class="container">
			<h1>Hola, los siguientes son mis proyectos</h1>
            <table>
                @csrf
                <tr>
                    <th>Nombre del Proyecto</th>
                    <th>Descripción</th>
                </tr>
                @foreach ($proyectos as $proyecto)
                    <tr>
                        <td>{{ $proyecto->nombre }}
                            <a href="{{ route('proyecto.edit', $proyecto->id) }}"> Editar</a>
                            <form action="{{route('proyecto.destroy', $proyecto->id)}}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que quieres eliminar esta proyecto?')">Eliminar</button>
                            </form>
                         
                        </td>
                        
                        <td>{{ $proyecto->descripcion }}</td>
                        
                    </tr>
                @endforeach
                
            </table>
            <div>
                <a href="{{ route('proyecto.create') }}" class="btn btn-primary">Crear proyecto</a>
            </div>
            <!-- <button>Create</button> -->
            <!-- <button><a href="proyecto/create.blade.php"><span class="btonClick">Create</span></a></button> -->
		</div>
	</body>
</html>